[env]
TERM = "xterm-256color"

[window]
title = ""

[font]
normal.family = "MesloLGS Nerd Font Mono"
size = 14

[keyboard]
 bindings = [
  # Ctrl+6 -> Ctrl+shift+6
  { key = "Key6", mods= "Control", chars= "\u001e" }
]
