export XDG_CONFIG_HOME=$HOME/.config/

source $HOME/antigen.zsh
antigen bundle 'zsh-users/zsh-syntax-highlighting'
antigen bundle 'zsh-users/zsh-autosuggestions'
antigen apply
autoload -U promptinit; promptinit

zstyle :prompt:pure:path color '#EAEAEA'
zstyle :prompt:pure:prompt:success color '#0076FF' # Blue
zstyle :prompt:pure:prompt:error color '#FF1A1A' # Red
zstyle :prompt:pure:execution_time color '#F7B955' # Yellow
zstyle :prompt:pure:git:dirty color '#FF0080' # Highligt - Alert
zstyle :prompt:pure:git:branch color '#F7B955'
zstyle :prompt:pure:git:stash show yes

path+=$HOME/github/dotfiles/bin/local

prompt pure

bindkey -s ^f "tmux-sessionizer\n"

alias ll='ls -lG'

export SC_PAT="aHNleXI3Z2xhbG1ycGFleWlidXNjazNyejMyc3BjNHQ2cHZvam9vd2xrZDR1cnN4eXQ1cQ=="

 export NVM_DIR="$HOME/.nvm"
  [ -s "/usr/local/opt/nvm/nvm.sh" ] && \. "/usr/local/opt/nvm/nvm.sh"  # This loads nvm
  [ -s "/usr/local/opt/nvm/etc/bash_completion.d/nvm" ] && \. "/usr/local/opt/nvm/etc/bash_completion.d/nvm"  # This loads nvm bash_completio

#THIS MUST BE AT THE END OF THE FILE FOR SDKMAN TO WORK!!!
export SDKMAN_DIR="/Users/nicholaswilcox/.sdkman"
[[ -s "/Users/nicholaswilcox/.sdkman/bin/sdkman-init.sh" ]] && source "/Users/nicholaswilcox/.sdkman/bin/sdkman-init.sh"
